server:
  port: 8082

spring:
  application:
    name: review-service

  datasource:
    url: jdbc:postgresql://localhost:5433/reviews
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

services:
  moderationService: http://localhost:8083/api/v1/moderation
  userService: http://localhost:8084/api/v1/users
  rppsService: http://localhost:8081/api/v1/practitioners