### Créer un avis
POST http://localhost:8082/api/v1/reviews
Content-Type: application/json

{
  "rppsId": "123456788",
  "userId": "user_2",
  "addressIds": ["cabinet_3"],
  "comment": "bof",
  "tags": [
    {
      "category": "HANDICAP",
      "vote": "NEGATIVE"
    },
    {
      "category": "GENRE",
      "vote": "POSITIVE"
    }
  ]
}
### Créer un avis 2
POST http://localhost:8082/api/v1/reviews
Content-Type: application/json

{
  "rppsId": "123456788",
  "userId": "user_3",
  "addressIds": ["cabinet_3"],
  "comment": "bof",
  "tags": [
    {
      "category": "HANDICAP",
      "vote": "NEGATIVE"
    },
    {
      "category": "GENRE",
      "vote": "NEUTRAL"
    }
  ]
}
### Créer un avis 3
POST http://localhost:8082/api/v1/reviews
Content-Type: application/json

{
  "rppsId": "123456788",
  "userId": "user_3",
  "addressIds": ["cabinet_3"],
  "comment": "moyen",
  "tags": [
    {
      "category": "HANDICAP",
      "vote": "NEUTRAL"
    },
    {
      "category": "GENRE",
      "vote": "POSITIVE"
    }
  ]
}
### Récupérer les avis d'un praticien
GET http://localhost:8082/api/v1/reviews/practitioner/123456788/stats