package com.lil.safetagreviewservice.domain;

public enum PathologyFamily {
    ANXIETY("Anxiété et troubles liés au stress", "L’anxiété est un sentiment de nervosité, d’inquiétude ou de malaise qui fait partie de l’expérience humaine normale. Elle est également présente dans de nombreuses affections mentales, y compris le trouble anxieux généralisé, le trouble panique et les phobies. Bien que chacun de ces troubles soit différent, ils se caractérisent tous par une souffrance et un dysfonctionnement spécifiquement liés à l’anxiété et la peur."),
    DISSOCIATIVE("Troubles Dissociatifs", "De nombreuses personnes rencontrent occasionnellement des problèmes mineurs liés à un vide dans leurs souvenirs, leurs perceptions, leur identité et leur conscience. Une personne peut, par exemple, aller quelque part en voiture, puis réaliser qu’elle ne se souvient plus du trajet. Cela peut être dû au fait qu’elle était absorbée (par des soucis personnels, une émission de radio ou une conversation avec un passager) ou simplement qu’elle rêvassait. Ce type de problème, que l’on appelle dissociation normale, ne perturbe généralement pas les activités quotidiennes."),
    EATING_DISORDER("Troubles des conduites alimentaires", "Les troubles des conduites alimentaires impliquent une perturbation de l’alimentation ou du comportement lié à l’alimentation, et comprennent généralement : anorexie, boulimie."),
    MOOD("Troubles de l'humeur", "Les troubles de l’humeur sont des affections mentales qui se traduisent par de longues périodes de tristesse excessive (dépression), d’exaltation excessive (manie), ou les deux (bipolarité). Dépression et manie constituent les deux extrêmes des troubles de l’humeur, et le trouble bipolaire inclut ces deux extrêmes. Les troubles de l’humeur affectent la capacité d’une personne à fonctionner et peuvent survenir chez les adultes, les adolescents ou les enfants."),
    OCD("Troubles obsessionels compulsifs et apparentés", "Le trouble obsessionnel compulsif se caractérise par des obsessions, des compulsions, ou les deux. Les obsessions sont des idées, des images ou des impulsions récurrentes, persistantes, non désirées et anxiogènes. Les compulsions (aussi appelées rituels) sont des actions particulières ou des actes mentaux que des personnes se sentent obligées d’effectuer de manière répétée, pour tenter d’atténuer ou de prévenir l’anxiété causée par les obsessions."),
    PARAPHILIA("Paraphilies et troubles paraphiliques", "Les paraphilies sont des fantasmes ou des comportements sexuels fréquents et intenses portant sur des objets inanimés, des enfants ou des adultes non consentants. La souffrance ou l’humiliation de la personne ou d’un partenaire peut également être impliquée. Les troubles paraphiliques sont des paraphilies entraînant une souffrance ou perturbant le fonctionnement du paraphile, ou nuisant ou susceptibles de nuire à une autre personne."),
    PERSONALITY("Troubles de la personnalité", "Les troubles de la personnalité sont des affections mentales caractérisées par des schémas omniprésents et persistants de pensées, de perception, de réaction et de relations qui entraînent une souffrance importante pour la personne et/ou nuisent considérablement à sa capacité à fonctionner."),
    SCHIZOPHRENIA("Schizophrénie et troubles apparentés", "La schizophrénie et les troubles psychotiques apparentés ( trouble délirant , trouble psychotique bref , trouble schizophréniforme , trouble schizo-affectif , et trouble de la personnalité schizotypique ) sont des maladies mentales caractérisées par divers types de symptômes appelés symptômes psychotiques, symptômes négatifs et dysfonctionnement cognitif."),
    GENDER_DYSPHORIA("Incongruité de genre et dysphorie de genre", "Le sexe fait référence aux caractéristiques et traits du sexe biologique (tels que les organes génitaux, les chromosomes) utilisés pour catégoriser une personne comme étant de sexe masculin ou féminin. L’identité de genre est le sentiment interne d’être un homme, une femme ou autre chose, qui peut correspondre ou non au sexe de naissance ou aux caractéristiques sexuelles (comme la pilosité faciale, la voix, les seins). L’incongruité de genre est une expérience marquée et persistante d’incompatibilité entre l’identité de genre d’une personne et le sexe de naissance. La dysphorie de genre est une gêne ou une souffrance liée à l’incongruité de genre. Le diagnostic est défini par la souffrance de la personne plutôt que par la présence d’une incongruité de genre."),
    SOMATOFORM("Troubles somatoformes et apparentés", "Les troubles somatoformes et apparentés sont des affections mentales caractérisées par une attention intense et excessive portée aux symptômes physiques (somatiques), entraînant une souffrance significative et/ou une perturbation du fonctionnement quotidien."),
    SUBSTANCE_ABUSE("Troubles liés à l'usage de substances", "Les médicaments et autres substances font partie intégrante de la vie de tous les jours de beaucoup de personnes, qu’elles soient utilisées à des fins médicales légales, comme une habitude (boire du café pour la caféine par exemple) ou à des fins récréatives (voir le tableau Substances utilisées à la fois à des fins médicales et pour des usages illicites)."),
    SUICIDAL_BEHAVIOR("Comportement suicidaire et automutilation", "Le suicide est la mort causée par un acte d’autodestruction destiné à provoquer la mort. Les comportements suicidaires font référence aux suicides effectifs, aux tentatives de suicide et aux idées suicidaires (pensées et idées concernant la tentative de suicide).");

    private final String label;
    private final String description;

    PathologyFamily(String label, String description) {
        this.label = label;
        this.description = description;
    }

    public String getLabel() { return label; }
    public String getDescription() { return description; }
}
